name: Tetris Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 3 * * *"   # codziennie o 03:00

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install GeckoDriver
      uses: browser-actions/setup-geckodriver@latest

    - name: Run tests
      run: pytest -m "not smoke" --maxfail=1

    - name: Upload screenshots
      if: always()    # zawsze uploaduj, nawet przy failu
      uses: actions/upload-artifact@v3
      with:
        name: selenium-screenshots
        path: screenshots/