name: Tetris Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 3 * * *"   # codziennie o 03:00

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Install GeckoDriver
      uses: browser-actions/setup-geckodriver@latest

    - name: Run tests
      run: pytest -m "not smoke" --maxfail=1

    - name: Upload screenshots
      if: always()    # zawsze uploaduj, nawet przy failu
      uses: actions/upload-artifact@v3
      with:
        name: selenium-screenshots
        path: screenshots/

    - name: Run tests with Allure
      run: pytest --allure-dir=allure-results

    - name: Upload Allure results
      uses: actions/upload-artifact@v3
      with:
        name: allure-results
        path: allure-results/

    - name: Generate Allure report
      run: |
          allure generate allure-results -o allure-report --clean

    - name: Upload Allure HTML report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report/

    - name: Generate HTML report
      run: pytest --html=report.html --self-contained-html

    - name: Upload HTML report
      uses: actions/upload-artifact@v3
      with:
        name: html-report
        path: report.html

    - name: Send email notification on failure
      if: failure()
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "Tetris Tests FAILED"
          to: "gblazusiak@gmail.com"
          from: "tetris-ci@domena.com"
          body: "Testy E2E dla Tetrisa zakończyły się błędem. Sprawdź artefakty."
          attachments: "screenshots/*.png"